//POST http://localhost:8383/api/auth
//Content-Type: application/json

//{
  //"numeUtilizator": "alexIon",
  //"email": "alex@mail.com",
  //"parola": "1234"
//}

GET http://localhost:8383/api/retete


